appVersion: v1
kind: Service
metadata:
  name: express-api
spec:
  type: LoadBalancer
  selector:
    app: express-api
   ports:
    - port: 80
      targetPort: 80

apiVersion: apps/v1
kind: Deployment
metadata:
  name: express-api
  labels:
    app: express-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: express-api
    templete:
      metadata:
        labels:
          app: express-api
      spec:
        containers:
        - name: express-api
          image: us-central1-docker.pkg.dev/GOOGLE_PROJECT/express-api/express-api:latest
