name: Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{ secrets.DOCKERHUB_USERNAME }}/express-api

    - name: Run the Docker Container
      run: docker run -d -p 80:80 ${{ secrets.DOCKERHUB_USERNAME }}/express-api

    - name: run tests
      uses: liatrio/github-actions/apprentice-action@v1.0.0

    - name: Push the docker image to Docker hub
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/express-api

