name: Running Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag express-api
    - name: Run the Docker Container
      run: docker run -d -p 80:80 express-api
    - name: run tests
      uses: liatrio/github-actions/apprentice-action@master
