name: Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
    
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{ secrets.DOCKERHUB_USERNAME }}/express-api
  
    - name: Run the Docker Container
      run: docker run -d -p 80:80 ${{ secrets.DOCKERHUB_USERNAME }}/express-api
      
    - name: run tests
      uses: liatrio/github-actions/apprentice-action@v1.0.0

    - name: Log in to Google Cloud
      uses: google-github-actions/auth@v0
      with:
        credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}

    - name: Configure Docker for Google Cloud
      run: gcloud auth configure-docker

    - name: tag Docker image For GCR
      run: docker tag ${{ secrets.DOCKERHUB_USERNAME }}/express-api gcr.io/${{ secrets.GCP_PROJECT_ID }}/express-api

    - name: Push the Docker image to Google Container Registry (GCR)
      run: docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/express-api

    - name: Deploy to Google Cloud Run
      run: |
        gcloud run deploy express-api \
          --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/express-api \
          --platform managed \
          --region us-central1 \
          --allow-unauthenticated
    
    - name: Push the docker image to Docker hub
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/express-api
      
