name: Google cloud Deployment

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install gcloud CLI
      uses: google-github-actions/setup-gcloud@v0
      with:
        project_id: ${{ secrets.GOOGLE_PROJECT }}
        service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        export_default_credentials: true

    - name: Authenticate with gcloud
      run: echo "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}" > /tmp/google-credentials.json

    - name: Authenticate Docker with Google Cloud
      run: gcloud auth configure-docker us-central1-docker.pkg.dev

    - name: Build and push Docker image
      env:
        GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT }}
      run: |
        docker build -t us-central1-docker.pkg.dev/$GOOGLE_PROJECT/express-api/express-api:latest .
        docker push us-central1-docker.pkg.dev/$GOOGLE_PROJECT/express-api/express-api:latest

    - name: Deploy to Google Cloud Run
      env:
        GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT }}
      run: |
        gcloud run deploy express-api \
          --image us-central1-docker.pkg.dev/$GOOGLE_PROJECT/express-api/express-api:latest \
          --platform managed \
          --region us-central1 \
          --allow-unauthenticated
